language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- bash .travis/readme_prep.sh
- pip install .
script:
- python -u pacssim/SimProcess.py
- python -u pacssim/ServerlessSimulator.py
- python -u pacssim/ServerlessTemporalSimulator.py
- python -u examples/sim_trace.py
before_deploy:
- bash .travis/readme_prep.sh
deploy:
  provider: pypi
  username: nima_mahmoudi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  password:
    secure: a8FBUhV/JCFXDHtWpwhp52VJbLQOV6Nqwos/ws0ibgFtvYUNGsf0OLAiAwn/7pEe59VgMZ4tBYnFiZBqyPwjMlhOBX+Sn99hkYFbXEChOShGADuMupZiqyLn1mFRQHlw0gzzKpoePUmve6tAVN1W3gJpizd37mpbsh0AMYc4xn9dQe1qdVReOpwDVvOI1R9AztbgLV150gVWZPfEZUtorKAgkchNC7k8LPlYD1dTpAKYpKRhZh4dQZj8rVmOtuQVknu1vlG6yok3UDB73SMjt66zM7OtVhDXzFaGFEHxf6MJf/gsuVnCONY8vIjd29nrheb/F9KEMJF87pmBKBkWZ/O3cg2p33FbJEiAiI2dKNxswfDVrLpEzVOmyacsH01C/+cXZ2cWPkCMZcdwgC5rBimLYkUW6zFusAsQxrdPZDWtm0r3X8Q2GyTMun0kHCN60v/RLlECpfsJAcYbWfTau/p7FR2ESHzXTDAXNV/k99moUE80IpTskGJIJtl+fPc0PEO3Rozyw73bhDiKf/yHw2ImymQxTyDGzCQGIGWIqXVmYJSPTBoD7mUPXNmul/5dmu7mfsvJ8YBcL5y5l4/BHzSFo8qvwwlNvqbsSWcFQNmRkK4nmdXMSAZTEgrJUsrXcatzpuUMzJQ6nhZuV+r1CEnCyQS1RfdPKqCTmol8l2M=
  on:
    branch: production
