name: API Docker CI

on:
  push:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      if: ${{ github.ref != 'refs/heads/master' }}
      run: |
        docker build -f ./api/Dockerfile -t simfaas-api ./
    - name: Docker Build & Push
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nimamahmoudi/simfaas-api
        cache_froms: python:3.6-slim,nimamahmoudi/simfaas-api
        path: ./
        dockerfile: ./api/Dockerfile
        registry: docker.io
        push: true
        tag_with_ref: true
        tag_with_sha: true
  jupyter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nimamahmoudi/jupyter-simfaas
        cache_froms: jupyter/datascience-notebook,nimamahmoudi/jupyter-simfaas
        path: ./
        dockerfile: ./Dockerfile
        registry: docker.io
        push: true
        tag_with_ref: true
        tag_with_sha: true
