name: Docker Image CI

on:
  push:
    branches:
      - production
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        cp -R ../simfaas ./simfaas
        docker build ./api/ -f ./api/Dockerfile -t simfaas-api
    - name: Docker Build & Push
      if: ${{ github.ref == 'refs/heads/production' }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nimamahmoudi/simfaas-api
        cache_froms: python:3.6-slim,nimamahmoudi/simfaas-api
        path: ./api/
        dockerfile: ./api/Dockerfile
        registry: docker.io
        push: true
        tag_with_ref: true
        tag_with_sha: true
