name: Docker Image CI

on:
  push:
    branches: [ production ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nimamahmoudi/simfaas-api
        cache_froms: python:3.6-slim,nimamahmoudi/simfaas-api
        path: ./api/
        dockerfile: ./api/Dockerfile
        registry: docker.io
        push: true
        tag_with_ref: true
        tag_with_sha: true
